### ISSUE TITLE
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by robomotic** [BlazingDB/blazingsql#1084]
I have installed BlazinSQL via conda:

`conda install -c blazingsql/label/cuda11.0 -c blazingsql -c rapidsai -c nvidia -c conda-forge -c defaults blazingsql python=3.7 -y
`
I am on CUDA 11.0 with Python 3.7.

This was successful:

The following packages will be downloaded:

```
    package                    |            build
    ---------------------------|-----------------
    alsa-lib-1.2.3             |       h516909a_0         560 KB  conda-forge
    blazingsql-0.16.0a         |cuda11.0_py37_271       157.8 MB  rapidsai-nightly
    dask-cuda-0.16.0a201015    |          py37_96          76 KB  rapidsai-nightly
    dask-cudf-0.16.0a201013    |py37_gdd3eb62847_1976          91 KB  rapidsai-nightly
    google-cloud-cpp-1.16.0    |       he4a878c_2         5.3 MB  conda-forge
    google-cloud-cpp-common-0.25.0|       he83eced_7         113 KB  conda-forge
    googleapis-cpp-0.10.0      |       h6b1abdc_4         3.6 MB  conda-forge
    jpype1-1.0.2               |   py37h99015e2_0         3.0 MB  conda-forge
    libcrc32c-1.1.1            |       he1b5a44_2          20 KB  conda-forge
    netifaces-0.10.9           |py37h8f50634_1003          17 KB  conda-forge
    openjdk-11.0.8             |       hacce0ff_0       173.3 MB  conda-forge
    pyhive-0.6.2               |     pyh9f0ad1d_0          37 KB  conda-forge
    sasl-0.2.1                 |py37h3340039_1002          56 KB  conda-forge
    sqlalchemy-1.3.20          |   py37h8f50634_0         1.8 MB  conda-forge
    thrift-0.13.0              |   py37h3340039_2         120 KB  conda-forge
    thrift_sasl-0.4.2          |   py37h8f50634_0          14 KB  conda-forge
    xorg-fixesproto-5.0        |    h14c3975_1002           8 KB  conda-forge
    xorg-inputproto-2.3.2      |    h14c3975_1002          18 KB  conda-forge
    xorg-libxfixes-5.0.3       |    h516909a_1004          17 KB  conda-forge
    xorg-libxi-1.7.10          |       h516909a_0          45 KB  conda-forge
    xorg-libxtst-1.2.3         |    h516909a_1002          31 KB  conda-forge
    xorg-recordproto-1.14.2    |    h516909a_1002           7 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       346.0 MB
```

However when I try to use it:

```
(rapids) root@9b9b0c2f360a:/rapids/clx# python
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
>>> from blazingsql import BlazingContext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/blazingsql/__init__.py", line 3, in <module>
    from pyblazing.apiv2.context import BlazingContext
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 10, in <module>
    from pyblazing.apiv2.filesystem import FileSystem
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/pyblazing/apiv2/filesystem.py", line 3, in <module>
    import cio
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

```
I checked the variable and seems fine:

```
(base) [jupyter@c109518 ~]$ echo $LD_LIBRARY_PATH
/usr/local/cuda-11.1/lib64:
```

I can see the shared so via:

`ls /usr/local/cuda-11.1/lib64`

What can I do to make pyblazing to see the library?

**Comment by williamBlazing** [comment]
Hello @robomotic I am not sure why its not seeing the library. But I am seeing a couple strange things from the output you are sending:
The channels you specified when installing were the stable channels for blazingsql and rapids ` -c blazingsql -c rapidsai`
but the packages installed came from the nightly channels:
```blazingsql-0.16.0a         |cuda11.0_py37_271       157.8 MB  rapidsai-nightly
    dask-cuda-0.16.0a201015    |          py37_96          76 KB  rapidsai-nightly
    dask-cudf-0.16.0a201013    |py37_gdd3eb62847_1976          91 KB  rapidsai-nightly
```

I would try again, with a new conda enviroment. We also recently did a new stable release. For cuda 11.0 and python 3.7, you will want to install as follows:
`conda install -c blazingsql/label/cuda11.0 -c rapidsai -c nvidia -c conda-forge -c defaults blazingsql python=3.7 cudatoolkit=11.0`

**Comment by williamBlazing** [comment]
@robomotic Closing issue for now. If issue still persists, please re-open the issue and let us know

**Comment by raybellwaves** [comment]
I came across this tonight

```
$ conda install -c blazingsql/label/cuda10.2 -c blazingsql -c rapidsai -c nvidia -c conda-forge -c defaults blazingsql adlfs python=3.7

>>> from blazingsql import BlazingContext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ray/local/bin/anaconda3/envs/test_env/lib/python3.7/site-packages/blazingsql/__init__.py", line 3, in <module>
    from pyblazing.apiv2.context import BlazingContext
  File "/home/ray/local/bin/anaconda3/envs/test_env/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 10, in <module>
    from pyblazing.apiv2.filesystem import FileSystem
  File "/home/ray/local/bin/anaconda3/envs/test_env/lib/python3.7/site-packages/pyblazing/apiv2/filesystem.py", line 3, in <module>
    import cio
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory
```

logs of conda build below
```
(test_env) ray@ray-MS-7B43:~$ conda install -c blazingsql/label/cuda10.2 -c blazingsql -c rapidsai -c nvidia -c conda-forge -c defaults blazingsql adlfs python=3.7
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ray/local/bin/anaconda3/envs/test_env

  added / updated specs:
    - adlfs
    - blazingsql
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    aiohttp-3.7.3              |   py37h4abf009_0         616 KB  conda-forge
    arrow-cpp-1.0.1            |py37h2318771_14_cuda        20.4 MB  conda-forge
    arrow-cpp-proc-2.0.0       |             cuda          23 KB  conda-forge
    aws-sdk-cpp-1.8.63         |       h9b98462_0         2.2 MB  conda-forge
    blazingsql-0.16.1          |  cuda10.2_py37_7       157.9 MB  blazingsql/label/cuda10.2
    bokeh-2.2.3                |   py37hc8dfbb8_0         7.0 MB  conda-forge
    boost-cpp-1.72.0           |       h9359b55_3        16.3 MB  conda-forge
    brotlipy-0.7.0             |py37hb5d75c8_1001         346 KB  conda-forge
    cffi-1.14.3                |   py37h261ae71_2         228 KB
    chardet-3.0.4              |py37he5f6b98_1008         170 KB  conda-forge
    cryptography-3.2.1         |   py37hc72a4ac_0         623 KB  conda-forge
    cudatoolkit-11.0.221       |       h6bb024c_0       953.0 MB  nvidia
    cudf-0.16.0                |cuda_11.0_py37_g2b8298f566_0        84.7 MB  rapidsai
    cudnn-8.0.0                |       cuda11.0_0       403.2 MB  nvidia
    cupy-7.8.0                 |   py37h0ce7dbb_0        28.4 MB  rapidsai
    cyrus-sasl-2.1.27          |       h063b49f_1         228 KB  conda-forge
    cytoolz-0.11.0             |   py37h8f50634_1         377 KB  conda-forge
    dask-cuda-0.16.0           |           py37_0          76 KB  rapidsai
    dask-cudf-0.16.0           |py37_g2b8298f566_0          89 KB  rapidsai
    distributed-2.30.1         |   py37h89c1867_0         1.0 MB  conda-forge
    dlpack-0.3                 |       he1b5a44_1          13 KB  conda-forge
    fastavro-1.2.0             |   py37h4abf009_0         383 KB  conda-forge
    fastrlock-0.5              |   py37h3340039_1          31 KB  conda-forge
    future-0.18.2              |   py37h89c1867_2         712 KB  conda-forge
    google-cloud-cpp-1.16.0    |       he4a878c_2         5.3 MB  conda-forge
    google-cloud-cpp-common-0.25.0|       he83eced_7         113 KB  conda-forge
    googleapis-cpp-0.10.0      |       h6b1abdc_4         3.6 MB  conda-forge
    grpc-cpp-1.32.0            |       h7997a97_1         3.3 MB  conda-forge
    gtest-1.10.0               |       h0efe328_4         254 KB  conda-forge
    jpype1-1.1.2               |   py37h99015e2_0         468 KB  conda-forge
    keyring-21.5.0             |   py37h89c1867_0          47 KB  conda-forge
    libcrc32c-1.1.1            |       he1b5a44_2          20 KB  conda-forge
    libcudf-0.16.0             |cuda11.0_g2b8298f566_0       193.4 MB  rapidsai
    libntlm-1.4                |    h516909a_1002          32 KB  conda-forge
    librmm-0.16.0              |cuda11.0_g1bcc7b1_0          49 KB  rapidsai
    libsodium-1.0.18           |       h36c2ea0_1         366 KB  conda-forge
    llvmlite-0.34.0            |   py37h5202443_2         322 KB  conda-forge
    markupsafe-1.1.1           |   py37hb5d75c8_2          27 KB  conda-forge
    msgpack-python-1.0.0       |   py37hc928c03_2          91 KB  conda-forge
    multidict-4.7.5            |   py37h8f50634_2          69 KB  conda-forge
    nccl-2.7.8.1               |     h4962215_100       144.5 MB  nvidia
    netifaces-0.10.9           |py37h8f50634_1003          17 KB  conda-forge
    numba-0.51.2               |   py37h9fdb41a_0         3.6 MB  conda-forge
    numpy-1.19.4               |   py37h7e9df27_1         5.2 MB  conda-forge
    pillow-8.0.1               |   py37h63a5d19_0         689 KB  conda-forge
    psutil-5.7.3               |   py37hb5d75c8_0         339 KB  conda-forge
    pyarrow-1.0.1              |py37hbeecfa9_14_cuda         2.2 MB  conda-forge
    pyhive-0.6.2               |     pyh9f0ad1d_0          37 KB  conda-forge
    pynvml-8.0.4               |             py_1          31 KB  conda-forge
    pysocks-1.7.1              |   py37he5f6b98_2          27 KB  conda-forge
    python_abi-3.7             |          1_cp37m           4 KB  conda-forge
    pyyaml-5.3.1               |   py37hb5d75c8_1         185 KB  conda-forge
    rmm-0.16.0                 |cuda_11.0_py37_g1bcc7b1_0         4.5 MB  rapidsai
    sasl-0.2.1                 |py37h3340039_1002          56 KB  conda-forge
    secretstorage-3.2.0        |   py37h89c1867_0          24 KB  conda-forge
    setuptools-49.6.0          |   py37he5f6b98_2         944 KB  conda-forge
    spdlog-1.7.0               |       hc9558a2_2         410 KB  conda-forge
    sqlalchemy-1.3.20          |   py37h8f50634_0         1.8 MB  conda-forge
    thrift-0.13.0              |   py37h3340039_2         120 KB  conda-forge
    thrift_sasl-0.4.2          |   py37h8f50634_0          14 KB  conda-forge
    tornado-6.1                |   py37h4abf009_0         645 KB  conda-forge
    yarl-1.6.3                 |   py37h4abf009_0         139 KB  conda-forge
    zeromq-4.3.3               |       h58526e2_3         288 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        2.00 GB

The following NEW packages will be INSTALLED:

  abseil-cpp         conda-forge/linux-64::abseil-cpp-20200225.2-he1b5a44_2
  adal               conda-forge/noarch::adal-1.2.5-pyh9f0ad1d_0
  adlfs              conda-forge/noarch::adlfs-0.5.7-pyhd8ed1ab_0
  aiohttp            conda-forge/linux-64::aiohttp-3.7.3-py37h4abf009_0
  arrow-cpp          conda-forge/linux-64::arrow-cpp-1.0.1-py37h2318771_14_cuda
  arrow-cpp-proc     conda-forge/linux-64::arrow-cpp-proc-2.0.0-cuda
  async-timeout      conda-forge/noarch::async-timeout-3.0.1-py_1000
  attrs              conda-forge/noarch::attrs-20.3.0-pyhd3deb0d_0
  aws-c-common       conda-forge/linux-64::aws-c-common-0.4.59-h36c2ea0_1
  aws-c-event-stream conda-forge/linux-64::aws-c-event-stream-0.1.6-had2084c_6
  aws-checksums      conda-forge/linux-64::aws-checksums-0.1.10-h4e93380_0
  aws-sdk-cpp        conda-forge/linux-64::aws-sdk-cpp-1.8.63-h9b98462_0
  azure-core         conda-forge/noarch::azure-core-1.9.0-pyhd3deb0d_0
  azure-datalake-st~ conda-forge/noarch::azure-datalake-store-0.0.51-pyh9f0ad1d_0
  azure-identity     conda-forge/noarch::azure-identity-1.4.1-pyh9f0ad1d_0
  azure-storage-blob conda-forge/noarch::azure-storage-blob-12.6.0-pyhd3deb0d_0
  blazingsql         blazingsql/label/cuda10.2/linux-64::blazingsql-0.16.1-cuda10.2_py37_7
  blinker            conda-forge/noarch::blinker-1.4-py_1
  bokeh              conda-forge/linux-64::bokeh-2.2.3-py37hc8dfbb8_0
  boost-cpp          conda-forge/linux-64::boost-cpp-1.72.0-h9359b55_3
  brotli             conda-forge/linux-64::brotli-1.0.9-he1b5a44_3
  brotlipy           conda-forge/linux-64::brotlipy-0.7.0-py37hb5d75c8_1001
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_3
  c-ares             conda-forge/linux-64::c-ares-1.17.1-h36c2ea0_0
  cffi               pkgs/main/linux-64::cffi-1.14.3-py37h261ae71_2
  chardet            conda-forge/linux-64::chardet-3.0.4-py37he5f6b98_1008
  click              conda-forge/noarch::click-7.1.2-pyh9f0ad1d_0
  cloudpickle        conda-forge/noarch::cloudpickle-1.6.0-py_0
  cryptography       conda-forge/linux-64::cryptography-3.2.1-py37hc72a4ac_0
  cudatoolkit        nvidia/linux-64::cudatoolkit-11.0.221-h6bb024c_0
  cudf               rapidsai/linux-64::cudf-0.16.0-cuda_11.0_py37_g2b8298f566_0
  cudnn              nvidia/linux-64::cudnn-8.0.0-cuda11.0_0
  cupy               rapidsai/linux-64::cupy-7.8.0-py37h0ce7dbb_0
  cyrus-sasl         conda-forge/linux-64::cyrus-sasl-2.1.27-h063b49f_1
  cytoolz            conda-forge/linux-64::cytoolz-0.11.0-py37h8f50634_1
  dask               conda-forge/noarch::dask-2.30.0-py_0
  dask-core          conda-forge/noarch::dask-core-2.30.0-py_0
  dask-cuda          rapidsai/linux-64::dask-cuda-0.16.0-py37_0
  dask-cudf          rapidsai/linux-64::dask-cudf-0.16.0-py37_g2b8298f566_0
  dbus               conda-forge/linux-64::dbus-1.13.0-h4e0c4b3_1000
  distributed        conda-forge/linux-64::distributed-2.30.1-py37h89c1867_0
  dlpack             conda-forge/linux-64::dlpack-0.3-he1b5a44_1
  expat              conda-forge/linux-64::expat-2.2.9-he1b5a44_2
  fastavro           conda-forge/linux-64::fastavro-1.2.0-py37h4abf009_0
  fastrlock          conda-forge/linux-64::fastrlock-0.5-py37h3340039_1
  freetype           conda-forge/linux-64::freetype-2.10.4-h7ca028e_0
  fsspec             conda-forge/noarch::fsspec-0.8.4-py_0
  future             conda-forge/linux-64::future-0.18.2-py37h89c1867_2
  gflags             conda-forge/linux-64::gflags-2.2.2-he1b5a44_1004
  glog               conda-forge/linux-64::glog-0.4.0-h49b9bf7_3
  google-cloud-cpp   conda-forge/linux-64::google-cloud-cpp-1.16.0-he4a878c_2
  google-cloud-cpp-~ conda-forge/linux-64::google-cloud-cpp-common-0.25.0-he83eced_7
  googleapis-cpp     conda-forge/linux-64::googleapis-cpp-0.10.0-h6b1abdc_4
  grpc-cpp           conda-forge/linux-64::grpc-cpp-1.32.0-h7997a97_1
  gtest              conda-forge/linux-64::gtest-1.10.0-h0efe328_4
  heapdict           conda-forge/noarch::heapdict-1.0.1-py_0
  icu                conda-forge/linux-64::icu-67.1-he1b5a44_0
  idna               conda-forge/noarch::idna-2.10-pyh9f0ad1d_0
  importlib-metadata conda-forge/noarch::importlib-metadata-2.0.0-py_1
  importlib_metadata conda-forge/noarch::importlib_metadata-2.0.0-1
  isodate            conda-forge/noarch::isodate-0.6.0-py_1
  jeepney            conda-forge/noarch::jeepney-0.6.0-pyhd8ed1ab_0
  jinja2             conda-forge/noarch::jinja2-2.11.2-pyh9f0ad1d_0
  jpeg               conda-forge/linux-64::jpeg-9d-h36c2ea0_0
  jpype1             conda-forge/linux-64::jpype1-1.1.2-py37h99015e2_0
  keyring            conda-forge/linux-64::keyring-21.5.0-py37h89c1867_0
  krb5               conda-forge/linux-64::krb5-1.17.2-h926e7f8_0
  lcms2              conda-forge/linux-64::lcms2-2.11-hcbb858e_1
  libblas            conda-forge/linux-64::libblas-3.9.0-3_openblas
  libcblas           conda-forge/linux-64::libcblas-3.9.0-3_openblas
  libcrc32c          conda-forge/linux-64::libcrc32c-1.1.1-he1b5a44_2
  libcudf            rapidsai/linux-64::libcudf-0.16.0-cuda11.0_g2b8298f566_0
  libcurl            conda-forge/linux-64::libcurl-7.71.1-hcdd3856_8
  libev              conda-forge/linux-64::libev-4.33-h516909a_1
  libevent           conda-forge/linux-64::libevent-2.1.10-hcdb4288_3
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.5.0-hae1eefd_17
  libgfortran4       conda-forge/linux-64::libgfortran4-7.5.0-hae1eefd_17
  liblapack          conda-forge/linux-64::liblapack-3.9.0-3_openblas
  libllvm10          conda-forge/linux-64::libllvm10-10.0.1-he513fc3_3
  libnghttp2         conda-forge/linux-64::libnghttp2-1.41.0-h8cfc5f6_2
  libntlm            conda-forge/linux-64::libntlm-1.4-h516909a_1002
  libopenblas        conda-forge/linux-64::libopenblas-0.3.12-pthreads_hb3c22a3_1
  libpng             conda-forge/linux-64::libpng-1.6.37-h21135ba_2
  libprotobuf        conda-forge/linux-64::libprotobuf-3.13.0.1-h8b12597_0
  librmm             rapidsai/linux-64::librmm-0.16.0-cuda11.0_g1bcc7b1_0
  libsodium          conda-forge/linux-64::libsodium-1.0.18-h36c2ea0_1
  libssh2            conda-forge/linux-64::libssh2-1.9.0-hab1572f_5
  libthrift          conda-forge/linux-64::libthrift-0.13.0-h5aa387f_6
  libtiff            conda-forge/linux-64::libtiff-4.1.0-h4f3a223_6
  libutf8proc        conda-forge/linux-64::libutf8proc-2.5.0-h516909a_2
  libwebp-base       conda-forge/linux-64::libwebp-base-1.1.0-h36c2ea0_3
  llvmlite           conda-forge/linux-64::llvmlite-0.34.0-py37h5202443_2
  locket             conda-forge/noarch::locket-0.2.0-py_2
  lz4-c              conda-forge/linux-64::lz4-c-1.9.2-he1b5a44_3
  markupsafe         conda-forge/linux-64::markupsafe-1.1.1-py37hb5d75c8_2
  msal               conda-forge/noarch::msal-1.6.0-pyhd3deb0d_0
  msal_extensions    conda-forge/linux-64::msal_extensions-0.2.2-py37hc8dfbb8_0
  msgpack-python     conda-forge/linux-64::msgpack-python-1.0.0-py37hc928c03_2
  msrest             conda-forge/noarch::msrest-0.6.19-pyh9f0ad1d_0
  msrestazure        conda-forge/noarch::msrestazure-0.6.2-py_0
  multidict          conda-forge/linux-64::multidict-4.7.5-py37h8f50634_2
  nccl               nvidia/linux-64::nccl-2.7.8.1-h4962215_100
  netifaces          conda-forge/linux-64::netifaces-0.10.9-py37h8f50634_1003
  numba              conda-forge/linux-64::numba-0.51.2-py37h9fdb41a_0
  numpy              conda-forge/linux-64::numpy-1.19.4-py37h7e9df27_1
  oauthlib           conda-forge/noarch::oauthlib-3.0.1-py_0
  olefile            conda-forge/noarch::olefile-0.46-pyh9f0ad1d_1
  openjdk            conda-forge/linux-64::openjdk-11.0.1-h516909a_1016
  orc                conda-forge/linux-64::orc-1.6.5-hd3605a7_0
  packaging          conda-forge/noarch::packaging-20.4-pyh9f0ad1d_0
  pandas             conda-forge/linux-64::pandas-1.1.4-py37h10a2094_0
  parquet-cpp        conda-forge/noarch::parquet-cpp-1.5.1-2
  partd              conda-forge/noarch::partd-1.1.0-py_0
  pillow             conda-forge/linux-64::pillow-8.0.1-py37h63a5d19_0
  portalocker        conda-forge/linux-64::portalocker-1.7.0-py37hc8dfbb8_1
  psutil             conda-forge/linux-64::psutil-5.7.3-py37hb5d75c8_0
  pyarrow            conda-forge/linux-64::pyarrow-1.0.1-py37hbeecfa9_14_cuda
  pycparser          conda-forge/noarch::pycparser-2.20-pyh9f0ad1d_2
  pyhive             conda-forge/noarch::pyhive-0.6.2-pyh9f0ad1d_0
  pyjwt              conda-forge/noarch::pyjwt-1.7.1-py_0
  pynvml             conda-forge/noarch::pynvml-8.0.4-py_1
  pyopenssl          conda-forge/noarch::pyopenssl-19.1.0-py_1
  pyparsing          conda-forge/noarch::pyparsing-2.4.7-pyh9f0ad1d_0
  pysocks            conda-forge/linux-64::pysocks-1.7.1-py37he5f6b98_2
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python_abi         conda-forge/linux-64::python_abi-3.7-1_cp37m
  pytz               conda-forge/noarch::pytz-2020.4-pyhd8ed1ab_0
  pyyaml             conda-forge/linux-64::pyyaml-5.3.1-py37hb5d75c8_1
  re2                conda-forge/linux-64::re2-2020.10.01-he1b5a44_0
  requests           conda-forge/noarch::requests-2.25.0-pyhd3deb0d_0
  requests-oauthlib  conda-forge/noarch::requests-oauthlib-1.3.0-pyh9f0ad1d_0
  rmm                rapidsai/linux-64::rmm-0.16.0-cuda_11.0_py37_g1bcc7b1_0
  sasl               conda-forge/linux-64::sasl-0.2.1-py37h3340039_1002
  secretstorage      conda-forge/linux-64::secretstorage-3.2.0-py37h89c1867_0
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  snappy             conda-forge/linux-64::snappy-1.1.8-he1b5a44_3
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.3.0-pyhd8ed1ab_0
  spdlog             conda-forge/linux-64::spdlog-1.7.0-hc9558a2_2
  sqlalchemy         conda-forge/linux-64::sqlalchemy-1.3.20-py37h8f50634_0
  tblib              conda-forge/noarch::tblib-1.6.0-py_0
  thrift             conda-forge/linux-64::thrift-0.13.0-py37h3340039_2
  thrift_sasl        conda-forge/linux-64::thrift_sasl-0.4.2-py37h8f50634_0
  toolz              conda-forge/noarch::toolz-0.11.1-py_0
  tornado            conda-forge/linux-64::tornado-6.1-py37h4abf009_0
  typing-extensions  conda-forge/noarch::typing-extensions-3.7.4.3-0
  typing_extensions  conda-forge/noarch::typing_extensions-3.7.4.3-py_0
  urllib3            conda-forge/noarch::urllib3-1.25.11-py_0
  yaml               conda-forge/linux-64::yaml-0.2.5-h516909a_0
  yarl               conda-forge/linux-64::yarl-1.6.3-py37h4abf009_0
  zeromq             conda-forge/linux-64::zeromq-4.3.3-h58526e2_3
  zict               conda-forge/noarch::zict-2.0.0-py_0
  zipp               conda-forge/noarch::zipp-3.4.0-py_0
  zstd               conda-forge/linux-64::zstd-1.4.5-h6597ccf_2

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2020.10.14~ --> conda-forge::ca-certificates-2020.11.8-ha878542_0
  certifi            pkgs/main/noarch::certifi-2020.6.20-p~ --> conda-forge/linux-64::certifi-2020.11.8-py37h89c1867_0

The following packages will be SUPERSEDED by a higher-priority channel:

  openssl              pkgs/main::openssl-1.1.1h-h7b6447c_0 --> conda-forge::openssl-1.1.1h-h516909a_0
  pip                pkgs/main/linux-64::pip-20.2.4-py38h0~ --> conda-forge/noarch::pip-20.2.4-py_0
  setuptools         pkgs/main::setuptools-50.3.1-py38h06a~ --> conda-forge::setuptools-49.6.0-py37he5f6b98_2

The following packages will be DOWNGRADED:

  python                                   3.8.5-h7579374_1 --> 3.7.9-h7579374_0


Proceed ([y]/n)? 


Downloading and Extracting Packages
brotlipy-0.7.0       | 346 KB    | ############################################################################################################################### | 100% 
cyrus-sasl-2.1.27    | 228 KB    | ############################################################################################################################### | 100% 
dask-cudf-0.16.0     | 89 KB     | ############################################################################################################################### | 100% 
cudf-0.16.0          | 84.7 MB   | ############################################################################################################################### | 100% 
chardet-3.0.4        | 170 KB    | ############################################################################################################################### | 100% 
jpype1-1.1.2         | 468 KB    | ############################################################################################################################### | 100% 
cytoolz-0.11.0       | 377 KB    | ############################################################################################################################### | 100% 
cudnn-8.0.0          | 403.2 MB  |                                                                                                                                 |   0% 



cudnn-8.0.0          | 403.2 MB  | ############################################################################################################################### | 100% 
pyarrow-1.0.1        | 2.2 MB    | ############################################################################################################################### | 100% 
msgpack-python-1.0.0 | 91 KB     | ############################################################################################################################### | 100% 
python_abi-3.7       | 4 KB      | ############################################################################################################################### | 100% 
pyhive-0.6.2         | 37 KB     | ############################################################################################################################### | 100% 
aiohttp-3.7.3        | 616 KB    | ############################################################################################################################### | 100% 
multidict-4.7.5      | 69 KB     | ############################################################################################################################### | 100% 
dlpack-0.3           | 13 KB     | ############################################################################################################################### | 100% 
aws-sdk-cpp-1.8.63   | 2.2 MB    | ############################################################################################################################### | 100% 
cffi-1.14.3          | 228 KB    | ############################################################################################################################### | 100% 
fastavro-1.2.0       | 383 KB    | ############################################################################################################################### | 100% 
psutil-5.7.3         | 339 KB    | ############################################################################################################################### | 100% 
future-0.18.2        | 712 KB    | ############################################################################################################################### | 100% 
grpc-cpp-1.32.0      | 3.3 MB    | ############################################################################################################################### | 100% 
librmm-0.16.0        | 49 KB     | ############################################################################################################################### | 100% 
libcudf-0.16.0       | 193.4 MB  | ############################################################################################################################### | 100% 
libcrc32c-1.1.1      | 20 KB     | ############################################################################################################################### | 100% 
netifaces-0.10.9     | 17 KB     | ############################################################################################################################### | 100% 
sqlalchemy-1.3.20    | 1.8 MB    | ############################################################################################################################### | 100% 
thrift_sasl-0.4.2    | 14 KB     | ############################################################################################################################### | 100% 
tornado-6.1          | 645 KB    | ############################################################################################################################### | 100% 
dask-cuda-0.16.0     | 76 KB     | ############################################################################################################################### | 100% 
pillow-8.0.1         | 689 KB    | ############################################################################################################################### | 100% 
arrow-cpp-1.0.1      | 20.4 MB   | ############################################################################################################################### | 100% 
googleapis-cpp-0.10. | 3.6 MB    | ############################################################################################################################### | 100% 
sasl-0.2.1           | 56 KB     | ############################################################################################################################### | 100% 
pysocks-1.7.1        | 27 KB     | ############################################################################################################################### | 100% 
fastrlock-0.5        | 31 KB     | ############################################################################################################################### | 100% 
cryptography-3.2.1   | 623 KB    | ############################################################################################################################### | 100% 
libsodium-1.0.18     | 366 KB    | ############################################################################################################################### | 100% 
numba-0.51.2         | 3.6 MB    | ############################################################################################################################### | 100% 
thrift-0.13.0        | 120 KB    | ############################################################################################################################### | 100% 
keyring-21.5.0       | 47 KB     | ############################################################################################################################### | 100% 
spdlog-1.7.0         | 410 KB    | ############################################################################################################################### | 100% 
blazingsql-0.16.1    | 157.9 MB  | ############################################################################################################################### | 100% 
boost-cpp-1.72.0     | 16.3 MB   | ############################################################################################################################### | 100% 
cudatoolkit-11.0.221 | 953.0 MB  |                                                                                                                                 |   0% 
cudatoolkit-11.0.221 | 953.0 MB  | ############################################################################################################################### | 100% 
pyyaml-5.3.1         | 185 KB    | ############################################################################################################################### | 100% 
zeromq-4.3.3         | 288 KB    | ############################################################################################################################### | 100% 
bokeh-2.2.3          | 7.0 MB    | ############################################################################################################################### | 100% 
gtest-1.10.0         | 254 KB    | ############################################################################################################################### | 100% 
google-cloud-cpp-com | 113 KB    | ############################################################################################################################### | 100% 
rmm-0.16.0           | 4.5 MB    | ############################################################################################################################### | 100% 
secretstorage-3.2.0  | 24 KB     | ############################################################################################################################### | 100% 
numpy-1.19.4         | 5.2 MB    | ############################################################################################################################### | 100% 
markupsafe-1.1.1     | 27 KB     | ############################################################################################################################### | 100% 
cupy-7.8.0           | 28.4 MB   | ############################################################################################################################### | 100% 
distributed-2.30.1   | 1.0 MB    | ############################################################################################################################### | 100% 
yarl-1.6.3           | 139 KB    | ############################################################################################################################### | 100% 
setuptools-49.6.0    | 944 KB    | ############################################################################################################################### | 100% 
pynvml-8.0.4         | 31 KB     | ############################################################################################################################### | 100% 
nccl-2.7.8.1         | 144.5 MB  | ############################################################################################################################### | 100% 
llvmlite-0.34.0      | 322 KB    | ############################################################################################################################### | 100% 
libntlm-1.4          | 32 KB     | ############################################################################################################################### | 100% 
google-cloud-cpp-1.1 | 5.3 MB    | ############################################################################################################################### | 100% 
arrow-cpp-proc-2.0.0 | 23 KB     | ############################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: - By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

done
```
