### ISSUE TITLE
An error is reported when the SQL statement is executed in Python service: Unable to instantiate java compiler

### ISSUE THREAD

**Issue by Wxinxiny** [BlazingDB/blazingsql#1366]
from blazingsql import BlazingContext
bc = BlazingContext()
df = pd.read_json(data)
bc.create_table(table_alise, df)
gdf = bc.sql(sql)
result = gdf.to_json()

Exception:
java.lang.IllegalStateException: Unable to instantiate java compiler
        at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.compile(JaninoRelMetadataProvider.java:433)
        at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.load3(JaninoRelMetadataProvider.java:374)
        at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.lambda$static$0(JaninoRelMetadataProvider.java:109)
        at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:151)
        ·····

File "/root/bsqlserver/gce_app/libs/bsql_util.py", line 22, in jsonstr_bsql_exec
  gdf = bc.sql(sql)
File "/usr/local/envs/bsql/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 2880, in sql
  except cio.RunQueryError as e:
AttributeError: module 'cio' has no attribute 'RunQueryError'

**Comment by Wxinxiny** [comment]
The following information is displayed:

BlazingSQL version (git hash): e139eca59fb3d75f0bc362077d4da69cb167b75b
BlazingSQL branch name: HEAD
BlazingSQL branch tag: v0.17.0
BlazingSQL build id: 0
BlazingSQL compiler version: GNU /usr/bin/c++ 7.5.0

**Comment by Wxinxiny** [comment]
> Hello @Wxinxiny could you please tell us what version you are using?
> you can get the version by typing:
> 
> ```
> import blazingsql
> blazingsql.__info__()
> ```
