### ISSUE TITLE
[BUG] Couldn't run blazing in distributed mode.

### ISSUE THREAD

**Issue by alexsisu** [BlazingDB/blazingsql#446]
**Describe the bug**
I have a 2 machine setup (1 gpu per machine) attached to a hdfs cluster.
When starting blazing in distributed mode. 
I run the dask-scheduler + dask workers.
I managed to run only one time the following code:
```
from blazingsql import BlazingContext

from dask.distributed import Client
import pyarrow.parquet as pq
import os
import time
import cudf
import os
from sys import platform

import psutil
from subprocess import Popen, PIPE
import subprocess
import re
import dask_cudf


client = Client('172.31.3.117:18085')

bc = BlazingContext(dask_client=client, network_interface='ens5',allocator="managed",pool=True)

# dask cudf
hd_fpath = "hdfs://172.31.3.117:9000/mnt/conduit_parquet_store/file_conduitbugbash_books15mil_MJXW623TGE2W22LM_snappy_parquet"
res = dask_cudf.read_parquet(hd_fpath)

bc.create_table("books", res)
# queries
queries = [("warmup", "select count(*) from `file_conduitbugbash`.`books15mil` limit 1"),
           ("count1", "select count(*) from `file_conduitbugbash`.`books15mil`"),
           ("count2", "select count(*) from `file_conduitbugbash`.`books15mil`"),
           ("agg1",
            "select a.`Year-Of-Publication`,count(a.`Publisher`) from `file_conduitbugbash`.`books15mil` a group by a.`Year-Of-Publication`"),
           ("agg2",
            "select a.`Year-Of-Publication`,count(ISBN) from `file_conduitbugbash`.`books15mil` a group by a.`Year-Of-Publication` limit 10"),
           ("agg3",
            "select a.`Year-Of-Publication`,count(a.`Book-Author`) from `file_conduitbugbash`.`books15mil` a group by a.`Year-Of-Publication` limit 10"),
           ("agg4",
            "select  a.`Book-Author`,count(a.`Year-Of-Publication`) from `file_conduitbugbash`.`books15mil`  a group by a.`Book-Author` limit 10"),
           ("agg5",
            "select  a.`Book-Author`,a.`Year-Of-Publication`,count(a.`Publisher`) from `file_conduitbugbash`.`books15mil`  a group by a.`Book-Author`,a.`Year-Of-Publication` limit 10"),
           ("q1",
            "select a.`ISBN`, a.`Book-Title`, a.`Book-Author`, a.`Year-Of-Publication`, a.`Publisher`, a.`Image-URL-S`, a.`Image-URL-M`, a.`Image-URL-L` FROM `file_conduitbugbash`.`books15mil` a limit 1000"),
           ("q2", "select count(a.`ISBN`) FROM `file_conduitbugbash`.`books15mil` a"),
           ("q3",
            "select a.`Publisher`, COUNT(a.`ISBN`) FROM `file_conduitbugbash`.`books15mil` a GROUP BY a.`Publisher` limit 1001"),
           ("q4",
            "select a.`Book-Author`, a.`Publisher`, COUNT(a.`ISBN`) FROM `file_conduitbugbash`.`books15mil` a GROUP BY a.`Book-Author`, a.`Publisher` limit 1001"),
           ("q5",
            "select a.`Book-Title`, COUNT(a.`ISBN`) FROM `file_conduitbugbash`.`books15mil` a GROUP BY a.`Book-Title` limit 1001"),
           ("q6",
            "select a.`Book-Title`, a.`Year-Of-Publication`, COUNT(a.`ISBN`) FROM `file_conduitbugbash`.`books15mil` a GROUP BY a.`Book-Title`, a.`Year-Of-Publication` limit 1001"),
           ("q7",
            "select C_43 AS C_1, C_0 AS C_3, C_4331 AS C_2 FROM (select a.`Book-Author` AS C_43, a.`Publisher` AS C_0, COUNT(a.`ISBN`) AS C_4331 FROM `file_conduitbugbash`.`books15mil` a GROUP BY a.`Book-Author`, a.`Publisher` ) C_4954424c WHERE ((CASE WHEN (C_4331 IS NULL ) THEN 1 ELSE CASE WHEN (C_4331 < 340) THEN 1 ELSE 0 END END = 1) OR (CASE WHEN (C_4331 IS NULL ) THEN 0 ELSE CASE WHEN (C_4331 = 340) THEN 1 ELSE 0 END END = 1) AND ((C_43 >= 'Dick King-Smith') AND (C_43 IS NOT NULL ) AND (C_0 IS NOT NULL ) AND (C_0 = 'Walker Books') OR (C_0 IS NOT NULL ) AND (C_0 > 'Walker Books'))) LIMIT 1001"),
           ("f1",
            "SELECT C_43 AS C_8, C_5 AS C_7, COUNT(C_0) AS C_4331 FROM (SELECT C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`ISBN` AS C_0, C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`Book-Title` AS C_1, C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`Book-Author` AS C_43, C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`Year-Of-Publication` AS C_5, C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`Publisher` AS C_2, C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`Image-URL-S` AS C_3, C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`Image-URL-M` AS C_4, C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`Image-URL-L` AS C_6 FROM `file_conduitbugbash`.`books15mil` C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c WHERE C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`Year-Of-Publication` IN ('2003', '2004', '2005', '2000', '2001', '2002') ) C_4954424c GROUP BY C_43, C_5 LIMIT 1001"),
           ("f2",
            "SELECT C_2 AS C_8, C_1 AS C_7, COUNT(C_4) AS C_4331 FROM (SELECT C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`ISBN` AS C_4, C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`Book-Title` AS C_5, C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`Book-Author` AS C_2, C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`Year-Of-Publication` AS C_3, C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`Publisher` AS C_1, C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`Image-URL-S` AS C_6, C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`Image-URL-M` AS C_43, C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`Image-URL-L` AS C_0 FROM `file_conduitbugbash`.`books15mil` C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c WHERE C_66696c655f636f6e64756974627567626173685f626f6f6b7331356d696c.`Year-Of-Publication` IN ('2003', '2004', '2005', '2000', '2001', '2002') ) C_4954424c GROUP BY C_2, C_1 LIMIT 1001")
           ]

all_executed_queries = []
for query_id, query in queries:
    query_to_execute = query.replace('`file_conduitbugbash`.`books15mil`', "books")
    start_time = time.time()
    bc.sql(query_to_execute)

    end_time = time.time()
    print(query_to_execute, ",", str(int((end_time - start_time) * 1000)) + "ms")

```

This above code runs successfully only once.
Trying to run it for the second time yields it just blocks when creating the blazing table with the following log in the RAL log file:
```
2020-03-03T12:37:51Z|1|TRACE|0|0|0|INITIALIZING RAL. RAL ID: 1, RAL Host: 172.31.3.117:13231, Network Interface: ens5, , Is Not Single Node, CUDA_VISIBLE_DEVICES is set to: 0, |||||
Node index 1 was using temporary node index identifier 1485263304
2020-03-03T12:56:41Z|1|TRACE|0|0|0|INITIALIZING RAL. RAL ID: 1, RAL Host: 172.31.3.117:16617, Network Interface: ens5, , Is Not Single Node, CUDA_VISIBLE_DEVICES is set to: 0, |||||
2020-03-03T12:56:48Z|1|TRACE|deregisterFileSystem: filesystem authority not found
```

Attach you have the RAL log.
**Environment details**
```
blazingsql                0.13.0a         cuda10.1_py37_154    blazingsql-nightly/label/cuda10.1
bsql-rapids-thirdparty    0.13.0                        3    blazingsql-nightly
bsql-toolchain            0.13.0                        3    blazingsql-nightly
bsql-toolchain-aws-cpp    0.13.0                        3    blazingsql-nightly
bsql-toolchain-gcp-cpp    0.13.0                        3    blazingsql-nightly
cudf                      0.13.0a200225         py37_2540    rapidsai-nightly
dask-cuda                 0.13.0b200225           py37_18    rapidsai-nightly
dask-cudf                 0.13.0a200225         py37_2540    rapidsai-nightly
libcudf                   0.13.0a200225     cuda10.1_2540    rapidsai-nightly
libnvstrings              0.13.0a200225     cuda10.1_2540    rapidsai-nightly
librmm                    0.13.0a200225      cuda10.1_281    rapidsai-nightly
nvstrings                 0.13.0a200225         py37_2540    rapidsai-nightly
rmm                       0.13.0a200225          py37_281    rapidsai-nightly
```
[RAL.1.log](https://github.com/BlazingDB/blazingsql/files/4286305/RAL.1.log)

**Comment by felipeblazing** [comment]
There was an issue with dfs there were not persisted e.g. without 

```
df = df.persist()
```

The new version handles that for you.

**Comment by alexsisu** [comment]
With the new build,  I noticed the following. One of the dask-workers dies, and after it reconnects nothing happens in the code. 
The code works fine , only one time. Second time I got a hang, and the following error message:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff676ccf156, pid=356, tid=0x00007ff534d7f700
#
# JRE version: OpenJDK Runtime Environment (8.0_192-b01) (build 1.8.0_192-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.192-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x14e156]
#
# Core dump written. Default location: //core or core.356
#
# An error report file with more information is saved as:
# //hs_err_pid356.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
#
[RAL.1.log](https://github.com/BlazingDB/blazingsql/files/4288939/RAL.1.log)
[RAL.0.log](https://github.com/BlazingDB/blazingsql/files/4288941/RAL.0.log)
[hs_err_pid356.log](https://github.com/BlazingDB/blazingsql/files/4288942/hs_err_pid356.log)



```

**Comment by alexsisu** [comment]
Attaching the files again. Not sure they got uploaded
[RAL.1.log](https://github.com/BlazingDB/blazingsql/files/4288949/RAL.1.log)
[RAL.0.log](https://github.com/BlazingDB/blazingsql/files/4288951/RAL.0.log)
[hs_err_pid356.log](https://github.com/BlazingDB/blazingsql/files/4288952/hs_err_pid356.log)

**Comment by alexsisu** [comment]
This are the errors I get with the new image:
Client:
```
File "perf_distributed_benchmark2.py", line 40, in <module>
    res = bc.unify_partitions(res)
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 1023, in unify_partitions
    result = dask.dataframe.from_delayed(dask_futures)
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/dask/dataframe/io/io.py", line 563, in from_delayed
    meta = delayed(make_meta)(dfs[0]).compute()
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/dask/base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/client.py", line 2595, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/client.py", line 1893, in gather
    asynchronous=asynchronous,
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/client.py", line 780, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/utils.py", line 348, in sync
    raise exc.with_traceback(tb)
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/utils.py", line 332, in f
    result[0] = yield future
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/client.py", line 1752, in _gather
    raise exception.with_traceback(traceback)
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 223, in workerUnifyPartitions
    input.get_partition(partition).compute())
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/dask/base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/client.py", line 2595, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/client.py", line 1893, in gather
    asynchronous=asynchronous,
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/client.py", line 780, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/utils.py", line 348, in sync
    raise exc.with_traceback(tb)
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/utils.py", line 332, in f
    result[0] = yield future
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/client.py", line 1781, in _gather
    response = await future
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/client.py", line 1822, in _gather_remote
    who_has, rpc=self.rpc, close=False
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/utils_comm.py", line 78, in gather_from_workers
    r = await c
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/worker.py", line 3219, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/utils_comm.py", line 391, in retry_operation
    operation=operation,
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/utils_comm.py", line 379, in retry
    return await coro()
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/worker.py", line 3206, in _get_data
    max_connections=max_connections,
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/core.py", line 540, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/comm/tcp.py", line 212, in read
    frames, deserialize=self.deserialize, deserializers=deserializers
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/comm/utils.py", line 75, in from_frames
    res = _from_frames()
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/comm/utils.py", line 61, in _from_frames
    frames, deserialize=deserialize, deserializers=deserializers
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/protocol/core.py", line 124, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 268, in deserialize
    return loads(header, frames)
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 80, in serialization_error_loads
    raise TypeError(msg)
TypeError: Could not serialize object of type DataFrame.
Traceback (most recent call last):
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 191, in serialize
    header, frames = dumps(x, context=context) if wants_context else dumps(x)
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 37, in dask_dumps
    dumps = dask_serialize.dispatch(type(x))
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/dask/utils.py", line 492, in dispatch
    register()
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/protocol/__init__.py", line 110, in _register_cudf
    from cudf.comm import serialize
  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/cudf/comm/serialize.py", line 12, in <module>
    cudf.core.groupby.groupby.Groupby,
AttributeError: module 'cudf.core.groupby.groupby' has no attribute 'Groupby'
```

On the dask-worker1:
```
distributed.worker - WARNING -  Compute Failed
Function:  workerUnifyPartitions
args:      (<dask_cudf.DataFrame | 10 tasks | 10 npartitions>, {'tcp://172.31.3.117:18100': [9, 8, 7, 5, 3, 1], 'tcp://172.31.10.47:18100': [6, 4, 2, 0]}, 1)
kwargs:    {}
Exception: TypeError('Could not serialize object of type DataFrame.\nTraceback (most recent call last):\n  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 191, in serialize\n    header, frames = dumps(x, context=context) if wants_context else dumps(x)\n  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 37, in dask_dumps\n    dumps = dask_serialize.dispatch(type(x))\n  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/dask/utils.py", line 492, in dispatch\n    register()\n  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/protocol/__init__.py", line 110, in _register_cudf\n    from cudf.comm import serialize\n  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/cudf/comm/serialize.py", line 12, in <module>\n    cudf.core.groupby.groupby.Groupby,\nAttributeError: module \'cudf.core.groupby.groupby\' has no attribute \'Groupby\'\n')
```

On dask worker2:
```
distributed.worker - WARNING -  Compute Failed
Function:  workerUnifyPartitions
args:      (<dask_cudf.DataFrame | 10 tasks | 10 npartitions>, {'tcp://172.31.3.117:18100': [9, 8, 7, 5, 3, 1], 'tcp://172.31.10.47:18100': [6, 4, 2, 0]}, 0)
kwargs:    {}
Exception: TypeError('Could not serialize object of type DataFrame.\nTraceback (most recent call last):\n  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 191, in serialize\n    header, frames = dumps(x, context=context) if wants_context else dumps(x)\n  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 37, in dask_dumps\n    dumps = dask_serialize.dispatch(type(x))\n  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/dask/utils.py", line 492, in dispatch\n    register()\n  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/distributed/protocol/__init__.py", line 110, in _register_cudf\n    from cudf.comm import serialize\n  File "/usr/local/envs/blazingsql/lib/python3.7/site-packages/cudf/comm/serialize.py", line 12, in <module>\n    cudf.core.groupby.groupby.Groupby,\nAttributeError: module \'cudf.core.groupby.groupby\' has no attribute \'Groupby\'\n')

```

**Comment by alexsisu** [comment]
Also when I'm running it without unifying partitions I get this:
```
[ERROR] CUDA error at: /usr/local/envs/blazingsql/include/rmm/device_buffer.hpp437: cudaErrorIllegalAddress an illegal memory access was encountered
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  for_each: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
distributed.nanny - INFO - Worker process 240 was killed by signal 6
```
on worker2

**Comment by kingice** [comment]
> Also when I'm running it without unifying partitions I get this:
> 
> ```
> [ERROR] CUDA error at: /usr/local/envs/blazingsql/include/rmm/device_buffer.hpp437: cudaErrorIllegalAddress an illegal memory access was encountered
> terminate called after throwing an instance of 'thrust::system::system_error'
>   what():  for_each: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
> distributed.nanny - INFO - Worker process 240 was killed by signal 6
> ```
> 
> on worker2

Got the same thing ,event on single node.
I guess may be something crashed inside,like the memory is exhausted.
