### ISSUE TITLE
[BUG] Run query error, when handling very large dataframes with strings

### ISSUE THREAD

**Issue by rommelDB** [BlazingDB/blazingsql#637]
**Describe the bug**
On a dask environment, Blazingsql throws an error when handling very large dataframes with strings even when it has enough GPU memory to store the output.

```
Traceback (most recent call last):
  File "script.py", line 203, in <module>
    result = main(bc)
  File "script.py", line 151, in main
    result_df = bc.sql(query_1)
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 1651, in sql
    result = dask.dataframe.from_delayed(dask_futures)
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/dask/dataframe/io/io.py", line 561, in from_delayed
    meta = delayed(make_meta)(dfs[0]).compute()
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/dask/base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/distributed/client.py", line 2595, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/distributed/client.py", line 1894, in gather
    asynchronous=asynchronous,
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/distributed/client.py", line 778, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/distributed/utils.py", line 348, in sync
    raise exc.with_traceback(tb)
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/distributed/utils.py", line 332, in f
    result[0] = yield future
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/distributed/client.py", line 1753, in _gather
    raise exception.with_traceback(traceback)
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 213, in collectPartitionsRunQuery
    config_options)
  File "bsql_engine/io/io.pyx", line 258, in cio.runQueryCaller
  File "bsql_engine/io/io.pyx", line 361, in cio.runQueryCaller
  File "bsql_engine/io/io.pyx", line 95, in cio.runQueryPython
cio.RunQueryError: [RunQuery Error] cuDF failure at: /conda/conda-bld/libcudf_1588271093864/work/cpp/src/strings/copying/concatenate.cu:232: total size of strings is too large for cudf column
```
**Steps/Code to reproduce bug**
ToDo

**Expected behavior**
No error should be thrown because data fits in local and distributed memory.

**Environment overview**
 - Environment location: Bare-metal
 - Method of cuDF install: conda nightly
 - Method of blazingsql install: sources branch-0.14

**Comment by williamBlazing** [comment]
This should no longer be an issue with the new bigger than GPU architecture. Is this reproducible @rommelDB ?

**Comment by rommelDB** [comment]
The issue was in fact reproducible with a blazingsql build from two weeks ago. Actually, the issue raises with large data just before gathering the output dataframe instead of the processing where the new bigger than GPU architecture works fine. I'll try to reproduce the issue again, maybe something changed.
