### ISSUE TITLE
[BUG] q03 from tpcx-bb sometimes crash using 10 GB dataset

### ISSUE THREAD

**Issue by Christian8491** [BlazingDB/blazingsql#848]
**Describe the bug**
Sometimes when execute q03 it crashes whit this message:

```
$ python tpcx-bb-query-03.py --data_dir=/home/christian/Desktop/Tpcx-bb/dataset/sf10/parquet/
WARNING: Count not make directory
WARNING:root:WARNING: Count not make directory
WARNING: Count not make directory
WARNING:root:WARNING: Count not make directory
listening: tcp://*:17943
BlazingContext ready
[11:25:40.303] [error] 1109567041|5|5|In Projection kernel batch 1 for LogicalProject(wcs_user_sk=[$2], tstamp=[$3], wcs_item_sk=[$4], wcs_sales_sk=[$5], i_category_id=[$7], wcs_user_sk0=[$1]). What: std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/new-15/include/rmm/mr/device/managed_memory_resource.hpp70: cudaErrorIllegalAddress an illegal memory access was encountered|||||
[11:25:40.475] [error] 1109567041|3|3|In PartitionSingleNode kernel batch 0 for LogicalSingleNodePartition(sort0=[$5], dir0=[ASC]). What: std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/new-15/include/rmm/mr/device/managed_memory_resource.hpp70: cudaErrorIllegalAddress an illegal memory access was encountered|||||
[11:25:40.711] [error] 1109567041|6|6|In PartwiseJoin kernel left_idx[1] right_ind[0] for PartwiseJoin(condition=[=($0, $6)], joinType=[inner]). What: std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/new-15/include/rmm/mr/device/managed_memory_resource.hpp70: cudaErrorIllegalAddress an illegal memory access was encountered|||||
std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/new-15/include/rmm/mr/device/managed_memory_resource.hpp70: cudaErrorIllegalAddress an illegal memory access was encountered[11:25:40.738] [error] 1109567041|0|0|In execute_plan. What: std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/new-15/include/rmm/mr/device/managed_memory_resource.hpp70: cudaErrorIllegalAddress an illegal memory access was encountered|||||

[11:25:40.738] [error] 1109567041|0|0|In runQuery. What: std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/new-15/include/rmm/mr/device/managed_memory_resource.hpp70: cudaErrorIllegalAddress an illegal memory access was encountered|||||
>>>>>>>>  [RunQuery Error] std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/new-15/include/rmm/mr/device/managed_memory_resource.hpp70: cudaErrorIllegalAddress an illegal memory access was encountered
distributed.worker - WARNING -  Compute Failed
Function:  collectPartitionsRunQuery
args:      (0, [{'worker': 'tcp://127.0.0.1:39901', 'ip': '127.0.0.1', 'communication_port': 17943}], [<pyblazing.apiv2.context.BlazingTable object at 0x7fb9380ad9d0>, <pyblazing.apiv2.context.BlazingTable object at 0x7fb9380b1b50>], ['          BindableTableScan(table=[[main, web_clickstreams]], filters=[[AND(IS NOT NULL($4), IS NOT NULL($3))]], projects=[[0, 1, 2, 3, 5]], aliases=[[$f0, $f1, $f2, wcs_item_sk, wcs_user_sk]])', '        LogicalTableScan(table=[[main, item_df]])'], [0, <DataType.DASK_CUDF: 5>], 1109567041, '{"expr": "LogicalProject(wcs_user_sk=[$0], tstamp=[$1], wcs_item_sk=[$2], wcs_sales_sk=[$3], i_category_id=[$4])", "children": [{"expr": "LogicalSort(sort0=[$5], dir0=[ASC])", "children": [{"expr": "LogicalProject(wcs_user_sk=[$2], tstamp=[$3], wcs_item_sk=[$4], wcs_sales_sk=[$5], i_category_id=[$7], wcs_user_sk0=[$1])", "children": [{"expr": "LogicalJoin(condition=[=($0, $6)], joinType=[inner])", "children": [{"expr": "LogicalProject(wcs_item_sk=[$3], wcs_user_sk=[$4], CAST=[C
kwargs:    {}
Exception: UnboundLocalError("local variable 'dfs' referenced before assignment")

Traceback (most recent call last):
  File "tpcx-bb-query-03.py", line 217, in <module>
    result = main(bc)
  File "tpcx-bb-query-03.py", line 179, in main
    merged_df = bc.sql(query)
  File "/home/christian/miniconda3/envs/new-15/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 2284, in sql
    meta_results = self.dask_client.gather(dask_futures)
  File "/home/christian/miniconda3/envs/new-15/lib/python3.7/site-packages/distributed/client.py", line 1974, in gather
    asynchronous=asynchronous,
  File "/home/christian/miniconda3/envs/new-15/lib/python3.7/site-packages/distributed/client.py", line 824, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/christian/miniconda3/envs/new-15/lib/python3.7/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/home/christian/miniconda3/envs/new-15/lib/python3.7/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/home/christian/miniconda3/envs/new-15/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/christian/miniconda3/envs/new-15/lib/python3.7/site-packages/distributed/client.py", line 1833, in _gather
    raise exception.with_traceback(traceback)
  File "/home/christian/miniconda3/envs/new-15/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 258, in collectPartitionsRunQuery
    meta = dask.dataframe.utils.make_meta(dfs[0])
UnboundLocalError: local variable 'dfs' referenced before assignment
/home/christian/miniconda3/envs/new-15/lib/python3.7/site-packages/distributed/client.py:4773: RuntimeWarning: coroutine 'wait_for' was never awaited
  c.close(timeout=2)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/home/christian/miniconda3/envs/new-15/lib/python3.7/site-packages/distributed/client.py:4773: RuntimeWarning: coroutine 'Client._close' was never awaited
  c.close(timeout=2)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Steps/Code to reproduce bug**
Execute query 03 from here`[]( https://github.com/BlazingDB/bz-tpcx-bb/blob/master/blazing_queries/q03/tpcx-bb-query-03.py)` 

**Expected behavior**
Should not crash.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [conda]

**Environment details**
blazing nightly

**Additional context**
How run it:  python tpcx-bb-query-03.py --data_dir=/home/christian/Desktop/Tpcx-bb/dataset/sf10/parquet/

Get data from here:
https://drive.google.com/drive/folders/1k97QbuGxwUhTG1vjq41uVVAvWzofIyXN

**Comment by Christian8491** [comment]
Just Tested. 10 GB data local

```
BlazingContext ready
/home/christian/miniconda3/envs/bsql/lib/python3.8/site-packages/cudf/core/frame.py:2135: UserWarning: When using a sequence of booleans for `ascending`, `na_position` flag is not yet supported and defaults to treating nulls as greater than all numbers
  warnings.warn(
/home/christian/miniconda3/envs/bsql/lib/python3.8/site-packages/cudf/core/frame.py:2135: UserWarning: When using a sequence of booleans for `ascending`, `na_position` flag is not yet supported and defaults to treating nulls as greater than all numbers
  warnings.warn(
distributed.worker - WARNING -  Compute Failed
Function:  subgraph_callable
args:      (< could not convert arg to str >, < could not convert arg to str >, 'from-delayed-f6149ca7ab91bd6e1a791c95e8e50c3c')
kwargs:    {}
Exception: MemoryError('std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/bsql/include/rmm/mr/device/managed_memory_resource.hpp72: cudaErrorIllegalAddress an illegal memory access was encountered')

[13:08:48.633] [error] 1100354778|4|4|In Projection kernel batch 0 for LogicalProject(purchased_item=[10001], lastviewed_item=[$0], cnt=[$1]). What: std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/bsql/include/rmm/mr/device/managed_memory_resource.hpp72: cudaErrorIllegalAddress an illegal memory access was encountered|||||
[13:08:48.634] [error] 1100354778|0|0|In execute_plan. What: std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/bsql/include/rmm/mr/device/managed_memory_resource.hpp72: cudaErrorIllegalAddress an illegal memory access was encountered|||||
[13:08:48.634] [error] 1100354778|0|0|In runQuery. What: std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/bsql/include/rmm/mr/device/managed_memory_resource.hpp72: cudaErrorIllegalAddress an illegal memory access was encountered|||||
std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/bsql/include/rmm/mr/device/managed_memory_resource.hpp72: cudaErrorIllegalAddress an illegal memory access was encountered
>>>>>>>>  [RunQuery Error] std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/bsql/include/rmm/mr/device/managed_memory_resource.hpp72: cudaErrorIllegalAddress an illegal memory access was encountered
distributed.worker - WARNING -  Compute Failed
Function:  collectPartitionsRunQuery
args:      (0, [{'worker': 'tcp://127.0.0.1:42697', 'ip': '127.0.0.1', 'communication_port': 27390}], [<pyblazing.apiv2.context.BlazingTable object at 0x7f38d05637c0>], ['      BindableTableScan(table=[[main, product_result]], projects=[[1]], aliases=[[lastviewed_item]])'], [<DataType.DASK_CUDF: 5>], 1100354778, '{"expr": "LogicalSort(sort0=[$0], sort1=[$2], sort2=[$1], dir0=[ASC], dir1=[DESC], dir2=[ASC], fetch=[100])", "children": [{"expr": "LogicalProject(purchased_item=[10001], lastviewed_item=[$0], cnt=[$1])", "children": [{"expr": "LogicalAggregate(group=[{0}], cnt=[COUNT($0)])", "children": [{"expr": "BindableTableScan(table=[[main, product_result]], projects=[[1]], aliases=[[lastviewed_item]])", "children": []}]}]}]}', 0, {b'TABLE_SCAN_KERNEL_NUM_THREADS': b'4', b'ORDER_BY_SAMPLES_RATIO': b'0.1', b'BLAZING_DEVICE_MEM_CONSUMPTION_THRESHOLD': b'0.95', b'JOIN_PARTITION_SIZE_THRESHOLD': b'400000000', b'BLAZING_CACHE_DIRECTORY': b'/tmp', b'BLAZ_HOST_MEM_CONSUMPTION_THRESHOLD': b'0.75'})
kwargs:    {}
Exception: RunQueryError('[RunQuery Error] std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/bsql/include/rmm/mr/device/managed_memory_resource.hpp72: cudaErrorIllegalAddress an illegal memory access was encountered')

Traceback (most recent call last):
  File "tpcx-bb-query-03.py", line 218, in <module>
    result = main(bc)
  File "tpcx-bb-query-03.py", line 205, in main
    result = bc.sql(last_query)
  File "/home/christian/miniconda3/envs/bsql/lib/python3.8/site-packages/pyblazing/apiv2/context.py", line 2347, in sql
    meta_results = self.dask_client.gather(dask_futures)
  File "/home/christian/miniconda3/envs/bsql/lib/python3.8/site-packages/distributed/client.py", line 1982, in gather
    return self.sync(
  File "/home/christian/miniconda3/envs/bsql/lib/python3.8/site-packages/distributed/client.py", line 832, in sync
    return sync(
  File "/home/christian/miniconda3/envs/bsql/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/home/christian/miniconda3/envs/bsql/lib/python3.8/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/home/christian/miniconda3/envs/bsql/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/christian/miniconda3/envs/bsql/lib/python3.8/site-packages/distributed/client.py", line 1847, in _gather
    raise exception.with_traceback(traceback)
  File "/home/christian/miniconda3/envs/bsql/lib/python3.8/site-packages/pyblazing/apiv2/context.py", line 253, in collectPartitionsRunQuery
    raise e
  File "/home/christian/miniconda3/envs/bsql/lib/python3.8/site-packages/pyblazing/apiv2/context.py", line 239, in collectPartitionsRunQuery
    dfs = cio.runQueryCaller(
  File "bsql_engine/io/io.pyx", line 303, in cio.runQueryCaller
  File "bsql_engine/io/io.pyx", line 406, in cio.runQueryCaller
  File "bsql_engine/io/io.pyx", line 104, in cio.runQueryPython
cio.RunQueryError: [RunQuery Error] std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/bsql/include/rmm/mr/device/managed_memory_resource.hpp72: cudaErrorIllegalAddress an illegal memory access was encountere 
```

**Comment by Christian8491** [comment]
Just tested locally whit 10 GB data

[14:52:00.802] [error] 2086741980|5|5|In PartwiseJoin kernel left_idx[0] right_ind[0] for PartwiseJoin(condition=[=($0, $4)], joinType=[inner]). What: std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/bsql/include/rmm/mr/device/managed_memory_resource.hpp72: cudaErrorIllegalAddress an illegal memory access was encountered|||||
[14:52:00.804] [error] 2086741980|7|7|In BindableTableScan kernel batch for BindableTableScan(table=[[main, web_clickstreams]], filters=[[AND(IS NOT NULL($4), IS NOT NULL($3))]], projects=[[0, 1, 2, 3, 5]], aliases=[[$f0, $f1, $f2, wcs_item_sk, wcs_user_sk]]). What: std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/bsql/include/rmm/mr/device/managed_memory_resource.hpp72: cudaErrorIllegalAddress an illegal memory access was encountered|||||
[14:52:00.827] [error] 2086741980|6|6|In Projection kernel batch 1 for LogicalProject(wcs_item_sk=[$3], wcs_user_sk=[$4], +=[+(*($0, 86400), $1)], CASE=[CASE(IS NOT NULL($2), CAST($2):BIGINT NOT NULL, 0:BIGINT)]). What: std::bad_alloc: CUDA error at: /home/christian/miniconda3/envs/bsql/include/rmm/mr/device/managed_memory_resource.hpp72: cudaErrorIllegalAddress an illegal memory access was encountered||||
